import streamlit as st
import urllib.parse
from datetime import datetime
import csv
import io
import json
import gspread
from google.oauth2.service_account import Credentials

# ==========================================
# 0. TRANSLATIONS (DİL SÖZLÜĞÜ)
# ==========================================
LANGUAGES = {
    "🇬🇧 English": {
        "title": "Maximum Hamam & Spa",
        "sub": "Luxury Turkish Bath Reservation in Kuşadası",
        "desc": "Please fill out the form below to request your reservation. We will confirm via WhatsApp.",
        "name": "Full Name *",
        "package": "Select Package",
        "people": "Number of People",
        "date": "Preferred Date",
        "time": "Preferred Time",
        "pickup": "I need Free Pick-up & Drop-off in Kuşadası",
        "hotel": "Hotel Name / Address (Leave blank if no pick-up needed)",
        "notes": "Special Requests (Allergies, pressure preference, etc.)",
        "btn_save": "Save Reservation Details",
        "err_name": "Please enter your Full Name.",
        "err_hotel": "Please provide your Hotel Name so we can arrange your driver.",
        "success": "Details saved successfully",
        "wa_link": "👉 Click here to send these details to our WhatsApp and confirm your booking!",
        "wa_greet": "Hello Maximum Hamam! I would like to confirm my booking:",
        "wa_id": "Reservation ID",
        "wa_name": "Name",
        "wa_pack": "Package",
        "wa_ppl": "People",
        "wa_date": "Date",
        "wa_time": "Time",
        "wa_pick": "Pick-up Hotel",
        "wa_notes": "Notes"
    },
    "🇹🇷 Türkçe": {
        "title": "Maximum Hamam & Spa",
        "sub": "Kuşadası'nda Lüks Türk Hamamı Rezervasyonu",
        "desc": "Rezervasyon talebiniz için lütfen aşağıdaki formu doldurun. WhatsApp üzerinden onaylayacağız.",
        "name": "Adınız ve Soyadınız *",
        "package": "Paket Seçin",
        "people": "Kişi Sayısı",
        "date": "Tercih Edilen Tarih",
        "time": "Tercih Edilen Saat",
        "pickup": "Kuşadası içi ücretsiz servis (Pick-up) istiyorum",
        "hotel": "Otel Adı / Adresi (Servis istemiyorsanız boş bırakın)",
        "notes": "Özel İstekleriniz (Alerji, masaj sertlik tercihi vb.)",
        "btn_save": "Rezervasyon Bilgilerini Kaydet",
        "err_name": "Lütfen Adınızı ve Soyadınızı giriniz.",
        "err_hotel": "Şoförümüzün sizi alabilmesi için lütfen Otel Adını giriniz.",
        "success": "Bilgiler başarıyla kaydedildi",
        "wa_link": "👉 Rezervasyonunuzu onaylamak ve bilgileri WhatsApp'tan göndermek için buraya tıklayın!",
        "wa_greet": "Merhaba Maximum Hamam! Rezervasyonumu onaylamak istiyorum:",
        "wa_id": "Rezervasyon No",
        "wa_name": "İsim",
        "wa_pack": "Paket",
        "wa_ppl": "Kişi",
        "wa_date": "Tarih",
        "wa_time": "Saat",
        "wa_pick": "Alınacak Otel",
        "wa_notes": "Notlar"
    },
    "🇩🇪 Deutsch": {
        "title": "Maximum Hamam & Spa",
        "sub": "Luxuriöse Türkische Bad-Reservierung in Kuşadası",
        "desc": "Bitte füllen Sie das untenstehende Formular aus. Wir werden es über WhatsApp bestätigen.",
        "name": "Vollständiger Name *",
        "package": "Paket auswählen",
        "people": "Anzahl der Personen",
        "date": "Bevorzugtes Datum",
        "time": "Bevorzugte Zeit",
        "pickup": "Ich benötige eine kostenlose Abholung in Kuşadası",
        "hotel": "Hotelname / Adresse (Leer lassen, falls keine Abholung benötigt wird)",
        "notes": "Spezielle Wünsche (Allergien, Druckpräferenz usw.)",
        "btn_save": "Reservierungsdetails speichern",
        "err_name": "Bitte geben Sie Ihren vollständigen Namen ein.",
        "err_hotel": "Bitte geben Sie Ihren Hotelnamen an, damit wir den Fahrer arrangieren können.",
        "success": "Details erfolgreich gespeichert",
        "wa_link": "👉 Klicken Sie hier, um diese Details an unser WhatsApp zu senden und zu bestätigen!",
        "wa_greet": "Hallo Maximum Hamam! Ich möchte meine Buchung bestätigen:",
        "wa_id": "Reservierungs-ID",
        "wa_name": "Name",
        "wa_pack": "Paket",
        "wa_ppl": "Personen",
        "wa_date": "Datum",
        "wa_time": "Uhrzeit",
        "wa_pick": "Abholhotel",
        "wa_notes": "Notizen"
    },
    "🇳🇱 Dutch": {
        "title": "Maximum Hamam & Spa",
        "sub": "Luxe Turks Bad Reservering in Kuşadası",
        "desc": "Vul het onderstaande formulier in om uw reservering aan te vragen. Wij bevestigen via WhatsApp.",
        "name": "Volledige Naam *",
        "package": "Selecteer Pakket",
        "people": "Aantal Personen",
        "date": "Voorkeursdatum",
        "time": "Voorkeurstijd",
        "pickup": "Ik heb gratis ophaalservice nodig in Kuşadası",
        "hotel": "Hotelnaam / Adres (Laat leeg als er geen ophaalservice nodig is)",
        "notes": "Speciale Verzoeken (Allergieën, drukvoorkeur, enz.)",
        "btn_save": "Reserveringsgegevens Opslaan",
        "err_name": "Vul alstublieft uw volledige naam in.",
        "err_hotel": "Geef uw hotelnaam op zodat we uw chauffeur kunnen regelen.",
        "success": "Gegevens succesvol opgeslagen",
        "wa_link": "👉 Klik hier om deze details naar onze WhatsApp te sturen en uw boeking te bevestigen!",
        "wa_greet": "Hallo Maximum Hamam! Ik wil graag mijn boeking bevestigen:",
        "wa_id": "Reserverings-ID",
        "wa_name": "Naam",
        "wa_pack": "Pakket",
        "wa_ppl": "Personen",
        "wa_date": "Datum",
        "wa_time": "Tijd",
        "wa_pick": "Ophaalhotel",
        "wa_notes": "Opmerkingen"
    },
    "🇧🇪 Vlaams (Flemenkçe)": {
        "title": "Maximum Hamam & Spa",
        "sub": "Luxe Turks Bad Reservatie in Kuşadası",
        "desc": "Vul het onderstaande formulier in om uw reservatie aan te vragen. Wij bevestigen via WhatsApp.",
        "name": "Volledige Naam *",
        "package": "Selecteer Pakket",
        "people": "Aantal Personen",
        "date": "Voorkeursdatum",
        "time": "Voorkeurstijd",
        "pickup": "Ik heb gratis ophaalservice nodig in Kuşadası",
        "hotel": "Hotelnaam / Adres (Laat leeg als er geen ophaalservice nodig is)",
        "notes": "Speciale Verzoeken (Allergieën, drukvoorkeur, enz.)",
        "btn_save": "Reservatiegegevens Opslaan",
        "err_name": "Vul alstublieft uw volledige naam in.",
        "err_hotel": "Geef uw hotelnaam op zodat we uw chauffeur kunnen regelen.",
        "success": "Gegevens succesvol opgeslagen",
        "wa_link": "👉 Klik hier om deze details naar onze WhatsApp te sturen en uw boeking te bevestigen!",
        "wa_greet": "Hallo Maximum Hamam! Ik wil graag mijn boeking bevestigen:",
        "wa_id": "Reservatie-ID",
        "wa_name": "Naam",
        "wa_pack": "Pakket",
        "wa_ppl": "Personen",
        "wa_date": "Datum",
        "wa_time": "Tijd",
        "wa_pick": "Ophaalhotel",
        "wa_notes": "Opmerkingen"
    },
    "🇫🇷 Français": {
        "title": "Maximum Hamam & Spa",
        "sub": "Réservation de Bain Turc de Luxe à Kuşadası",
        "desc": "Veuillez remplir le formulaire ci-dessous. Nous confirmerons via WhatsApp.",
        "name": "Nom Complet *",
        "package": "Sélectionner le Forfait",
        "people": "Nombre de Personnes",
        "date": "Date Préférée",
        "time": "Heure Préférée",
        "pickup": "J'ai besoin d'une navette gratuite à Kuşadası",
        "hotel": "Nom / Adresse de l'Hôtel (Laissez vide si non nécessaire)",
        "notes": "Demandes Spéciales (Allergies, préférence de pression, etc.)",
        "btn_save": "Enregistrer les Détails",
        "err_name": "Veuillez entrer votre nom complet.",
        "err_hotel": "Veuillez indiquer le nom de votre hôtel pour le chauffeur.",
        "success": "Détails enregistrés avec succès",
        "wa_link": "👉 Cliquez ici pour envoyer ces détails sur notre WhatsApp et confirmer!",
        "wa_greet": "Bonjour Maximum Hamam! Je souhaite confirmer ma réservation:",
        "wa_id": "ID de Réservation",
        "wa_name": "Nom",
        "wa_pack": "Forfait",
        "wa_ppl": "Personnes",
        "wa_date": "Date",
        "wa_time": "Heure",
        "wa_pick": "Hôtel de ramassage",
        "wa_notes": "Notes"
    },
    "🇸🇪 Svenska": {
        "title": "Maximum Hamam & Spa",
        "sub": "Bokning av Lyxigt Turkiskt Bad i Kuşadası",
        "desc": "Vänligen fyll i formuläret nedan för att begära din bokning. Vi bekräftar via WhatsApp.",
        "name": "Fullständigt Namn *",
        "package": "Välj Paket",
        "people": "Antal Personer",
        "date
